import { Theme } from "./types";

const DARK_COLORS: { name: string; hex: string }[] = [
  { name: "Background", hex: "#0d1117" },
  { name: "Foreground", hex: "#c9d1d9" },
  { name: "Accent", hex: "#58a6ff" },
  { name: "Keyword", hex: "#ff7b72" },
  { name: "String", hex: "#a5d6ff" },
  { name: "Comment", hex: "#8b949e" },
  { name: "Variable", hex: "#ffa657" },
  { name: "Function", hex: "#d2a8ff" },
];

const LIGHT_COLORS: { name: string; hex: string }[] = [
  { name: "Background", hex: "#faf4ed" },
  { name: "Foreground", hex: "#575279" },
  { name: "Accent", hex: "#797593" },
  { name: "Keyword", hex: "#1e1e2e" },
  { name: "String", hex: "#ea9d34" },
  { name: "Comment", hex: "#9893a5" },
  { name: "Variable", hex: "#d7827e" },
  { name: "Function", hex: "#286983" },
];

export const SAMPLE_THEMES: Theme[] = [
  {
    id: "1",
    name: "Cybersunset",
    publisher: "novaop",
    publisherId: "novaop",
    description: "Neon-drenched cyberpunk palette with hot pinks and electric blues over deep charcoal",
    installs: 4200,
    rating: 4.8,
    ratingCount: 31,
    lastUpdated: "2026-04-22T00:00:00Z",
    repository: "https://github.com/novaop/cybersunset",
    type: "dark",
    categories: ["cyberpunk", "neon", "dark"],
    colors: [
      { name: "Background", hex: "#0a0a12" },
      { name: "Foreground", hex: "#e0d4f5" },
      { name: "Accent", hex: "#ff2d95" },
      { name: "Keyword", hex: "#00f0ff" },
      { name: "String", hex: "#ffd639" },
      { name: "Comment", hex: "#5a4a7a" },
      { name: "Variable", hex: "#c792ea" },
      { name: "Function", hex: "#82aaff" },
    ],
    iconUrl: null,
    vscodeId: "novaop.cybersunset",
    trendingScore: 94.2,
  },
  {
    id: "2",
    name: "Soft Pastel Dream",
    publisher: "kaiyuri",
    publisherId: "kaiyuri",
    description: "Gentle pastel hues layered over warm cream for a soothing coding experience",
    installs: 8700,
    rating: 4.6,
    ratingCount: 44,
    lastUpdated: "2026-04-18T00:00:00Z",
    repository: "https://github.com/kaiyuri/soft-pastel-dream",
    type: "light",
    categories: ["pastel", "light", "soft"],
    colors: [
      { name: "Background", hex: "#fff5f0" },
      { name: "Foreground", hex: "#6b5b73" },
      { name: "Accent", hex: "#f2a8c4" },
      { name: "Keyword", hex: "#c9728a" },
      { name: "String", hex: "#7db8a0" },
      { name: "Comment", hex: "#c4b5cd" },
      { name: "Variable", hex: "#a8907e" },
      { name: "Function", hex: "#8aa0c4" },
    ],
    iconUrl: null,
    vscodeId: "kaiyuri.soft-pastel-dream",
    trendingScore: 88.5,
  },
  {
    id: "3",
    name: "Terracotta Dusk",
    publisher: "mudstone",
    publisherId: "mudstone",
    description: "Warm earth tones and clay reds meet dark twilight for a grounded aesthetic",
    installs: 12500,
    rating: 4.5,
    ratingCount: 67,
    lastUpdated: "2026-03-30T00:00:00Z",
    repository: "https://github.com/mudstone/terracotta-dusk",
    type: "dark",
    categories: ["warm", "earth", "dark"],
    colors: [
      { name: "Background", hex: "#1a1210" },
      { name: "Foreground", hex: "#d4c4b0" },
      { name: "Accent", hex: "#c4623a" },
      { name: "Keyword", hex: "#e8a87c" },
      { name: "String", hex: "#b5a27d" },
      { name: "Comment", hex: "#6b5a4e" },
      { name: "Variable", hex: "#d4a07a" },
      { name: "Function", hex: "#8fb8a0" },
    ],
    iconUrl: null,
    vscodeId: "mudstone.terracotta-dusk",
    trendingScore: 78.1,
  },
  {
    id: "4",
    name: "Jade Garden",
    publisher: "bonsaicode",
    publisherId: "bonsaicode",
    description: "Green-tinted dark theme inspired by mossy zen gardens and bamboo forests",
    installs: 6300,
    rating: 4.9,
    ratingCount: 52,
    lastUpdated: "2026-04-20T00:00:00Z",
    repository: "https://github.com/bonsaicode/jade-garden",
    type: "dark",
    categories: ["green", "zen", "dark"],
    colors: [
      { name: "Background", hex: "#0b1a0e" },
      { name: "Foreground", hex: "#c2d4b6" },
      { name: "Accent", hex: "#4caf7d" },
      { name: "Keyword", hex: "#a8d8a0" },
      { name: "String", hex: "#e0d4a0" },
      { name: "Comment", hex: "#4a6b4f" },
      { name: "Variable", hex: "#7ecba1" },
      { name: "Function", hex: "#8cc4a0" },
    ],
    iconUrl: null,
    vscodeId: "bonsaicode.jade-garden",
    trendingScore: 96.7,
  },
  {
    id: "5",
    name: "Monochrome Ink",
    publisher: "sumidev",
    publisherId: "sumidev",
    description: "Pure black and white with grayscale gradients, inspired by ink wash painting",
    installs: 3100,
    rating: 4.3,
    ratingCount: 18,
    lastUpdated: "2026-02-10T00:00:00Z",
    repository: "https://github.com/sumidev/monochrome-ink",
    type: "dark",
    categories: ["monochrome", "minimal", "dark"],
    colors: [
      { name: "Background", hex: "#0e0e0e" },
      { name: "Foreground", hex: "#d4d4d4" },
      { name: "Accent", hex: "#808080" },
      { name: "Keyword", hex: "#b0b0b0" },
      { name: "String", hex: "#9e9e9e" },
      { name: "Comment", hex: "#555555" },
      { name: "Variable", hex: "#a8a8a8" },
      { name: "Function", hex: "#c0c0c0" },
    ],
    iconUrl: null,
    vscodeId: "sumidev.monochrome-ink",
    trendingScore: 72.4,
  },
  {
    id: "6",
    name: "Sepia Scholar",
    publisher: "parchment",
    publisherId: "parchment",
    description: "Aged paper and brown ink aesthetic for a vintage manuscript feel",
    installs: 5600,
    rating: 4.4,
    ratingCount: 29,
    lastUpdated: "2026-03-15T00:00:00Z",
    repository: "https://github.com/parchment/sepia-scholar",
    type: "light",
    categories: ["sepia", "vintage", "light"],
    colors: [
      { name: "Background", hex: "#f4ecd8" },
      { name: "Foreground", hex: "#4a3f2f" },
      { name: "Accent", hex: "#8b7355" },
      { name: "Keyword", hex: "#5c3d2e" },
      { name: "String", hex: "#6b5b3e" },
      { name: "Comment", hex: "#a89a7e" },
      { name: "Variable", hex: "#7a5c3a" },
      { name: "Function", hex: "#3d5a4e" },
    ],
    iconUrl: null,
    vscodeId: "parchment.sepia-scholar",
    trendingScore: 81.9,
  },
  {
    id: "7",
    name: "Abyssal Tide",
    publisher: "pelagics",
    publisherId: "pelagics",
    description: "Deep ocean blues and bioluminescent accents from the midnight zone",
    installs: 19000,
    rating: 4.7,
    ratingCount: 112,
    lastUpdated: "2026-04-12T00:00:00Z",
    repository: "https://github.com/pelagics/abyssal-tide",
    type: "dark",
    categories: ["ocean", "blue", "dark"],
    colors: [
      { name: "Background", hex: "#020c1b" },
      { name: "Foreground", hex: "#a8c7e2" },
      { name: "Accent", hex: "#00b4d8" },
      { name: "Keyword", hex: "#48cae4" },
      { name: "String", hex: "#90e0ef" },
      { name: "Comment", hex: "#1b3a5c" },
      { name: "Variable", hex: "#7eb8da" },
      { name: "Function", hex: "#0096c7" },
    ],
    iconUrl: null,
    vscodeId: "pelagics.abyssal-tide",
    trendingScore: 84.6,
  },
  {
    id: "8",
    name: "Neon Moss",
    publisher: "biolum",
    publisherId: "biolum",
    description: "Luminous greens and teals cascading over near-black backgrounds",
    installs: 7800,
    rating: 4.6,
    ratingCount: 58,
    lastUpdated: "2026-04-05T00:00:00Z",
    repository: "https://github.com/biolum/neon-moss",
    type: "dark",
    categories: ["green", "neon", "dark"],
    colors: DARK_COLORS,
    iconUrl: null,
    vscodeId: "biolum.neon-moss",
    trendingScore: 86.3,
  },
  {
    id: "9",
    name: "Rose Quartz",
    publisher: "mineralui",
    publisherId: "mineralui",
    description: "Delicate pink and rose tones on soft white for an elegant light theme",
    installs: 14200,
    rating: 4.5,
    ratingCount: 89,
    lastUpdated: "2026-03-28T00:00:00Z",
    repository: "https://github.com/mineralui/rose-quartz",
    type: "light",
    categories: ["pink", "elegant", "light"],
    colors: LIGHT_COLORS,
    iconUrl: null,
    vscodeId: "mineralui.rose-quartz",
    trendingScore: 74.8,
  },
  {
    id: "10",
    name: "Rust Forge",
    publisher: "ironwood",
    publisherId: "ironwood",
    description: "Oxidized oranges and burnt siennas against dark iron-gray backgrounds",
    installs: 4500,
    rating: 4.2,
    ratingCount: 22,
    lastUpdated: "2026-01-20T00:00:00Z",
    repository: "https://github.com/ironwood/rust-forge",
    type: "dark",
    categories: ["warm", "orange", "dark"],
    colors: [
      { name: "Background", hex: "#18120e" },
      { name: "Foreground", hex: "#d4c0a8" },
      { name: "Accent", hex: "#c45c2a" },
      { name: "Keyword", hex: "#e07040" },
      { name: "String", hex: "#d4a060" },
      { name: "Comment", hex: "#6b5444" },
      { name: "Variable", hex: "#b87333" },
      { name: "Function", hex: "#c49070" },
    ],
    iconUrl: null,
    vscodeId: "ironwood.rust-forge",
    trendingScore: 65.1,
  },
  {
    id: "11",
    name: "Aurora Terminal",
    publisher: "borealis",
    publisherId: "borealis",
    description: "Northern lights greens, purples, and pinks dancing across polar dark",
    installs: 28000,
    rating: 4.8,
    ratingCount: 156,
    lastUpdated: "2026-04-25T00:00:00Z",
    repository: "https://github.com/borealis/aurora-terminal",
    type: "dark",
    categories: ["aurora", "colorful", "dark"],
    colors: [
      { name: "Background", hex: "#05080f" },
      { name: "Foreground", hex: "#c8d8e8" },
      { name: "Accent", hex: "#50fa7b" },
      { name: "Keyword", hex: "#bd93f9" },
      { name: "String", hex: "#f1fa8c" },
      { name: "Comment", hex: "#3a4a6a" },
      { name: "Variable", hex: "#ff79c6" },
      { name: "Function", hex: "#8be9fd" },
    ],
    iconUrl: null,
    vscodeId: "borealis.aurora-terminal",
    trendingScore: 91.5,
  },
  {
    id: "12",
    name: "Sandstorm",
    publisher: "dunebug",
    publisherId: "dunebug",
    description: "Desert sand and amber tones with subtle warmth on off-white",
    installs: 3400,
    rating: 4.1,
    ratingCount: 15,
    lastUpdated: "2026-02-22T00:00:00Z",
    repository: "https://github.com/dunebug/sandstorm",
    type: "light",
    categories: ["desert", "warm", "light"],
    colors: [
      { name: "Background", hex: "#f5efe0" },
      { name: "Foreground", hex: "#3e3529" },
      { name: "Accent", hex: "#c4a35a" },
      { name: "Keyword", hex: "#8a6d3b" },
      { name: "String", hex: "#6b8a5e" },
      { name: "Comment", hex: "#b0a088" },
      { name: "Variable", hex: "#9e7a4a" },
      { name: "Function", hex: "#5a7a8a" },
    ],
    iconUrl: null,
    vscodeId: "dunebug.sandstorm",
    trendingScore: 58.3,
  },
  {
    id: "13",
    name: "Violet Nebula",
    publisher: "cosmik",
    publisherId: "cosmik",
    description: "Deep space purples and cosmic violets scattered across starless black",
    installs: 11500,
    rating: 4.7,
    ratingCount: 78,
    lastUpdated: "2026-04-15T00:00:00Z",
    repository: "https://github.com/cosmik/violet-nebula",
    type: "dark",
    categories: ["purple", "space", "dark"],
    colors: [
      { name: "Background", hex: "#0c0618" },
      { name: "Foreground", hex: "#d0c0e8" },
      { name: "Accent", hex: "#a855f7" },
      { name: "Keyword", hex: "#c084fc" },
      { name: "String", hex: "#e9d5ff" },
      { name: "Comment", hex: "#4a3568" },
      { name: "Variable", hex: "#d8b4fe" },
      { name: "Function", hex: "#818cf8" },
    ],
    iconUrl: null,
    vscodeId: "cosmik.violet-nebula",
    trendingScore: 89.4,
  },
  {
    id: "14",
    name: "Glacier Mist",
    publisher: "fjordworks",
    publisherId: "fjordworks",
    description: "Icy whites and pale blues evoking frozen Scandinavian landscapes",
    installs: 9200,
    rating: 4.3,
    ratingCount: 47,
    lastUpdated: "2026-03-10T00:00:00Z",
    repository: "https://github.com/fjordworks/glacier-mist",
    type: "light",
    categories: ["ice", "nordic", "light"],
    colors: [
      { name: "Background", hex: "#f0f4f8" },
      { name: "Foreground", hex: "#2d3748" },
      { name: "Accent", hex: "#90cdf4" },
      { name: "Keyword", hex: "#4a5568" },
      { name: "String", hex: "#68d391" },
      { name: "Comment", hex: "#a0aec0" },
      { name: "Variable", hex: "#63b3ed" },
      { name: "Function", hex: "#b794f4" },
    ],
    iconUrl: null,
    vscodeId: "fjordworks.glacier-mist",
    trendingScore: 70.2,
  },
  {
    id: "15",
    name: "Crimson Code",
    publisher: "scarletdev",
    publisherId: "scarletdev",
    description: "Blood reds and deep crimsons on obsidian for intense focus",
    installs: 2300,
    rating: 4.5,
    ratingCount: 14,
    lastUpdated: "2026-01-28T00:00:00Z",
    repository: "https://github.com/scarletdev/crimson-code",
    type: "dark",
    categories: ["red", "intense", "dark"],
    colors: [
      { name: "Background", hex: "#120808" },
      { name: "Foreground", hex: "#e8c8c8" },
      { name: "Accent", hex: "#dc143c" },
      { name: "Keyword", hex: "#ff4444" },
      { name: "String", hex: "#ff8888" },
      { name: "Comment", hex: "#6b3030" },
      { name: "Variable", hex: "#e06060" },
      { name: "Function", hex: "#ff6b6b" },
    ],
    iconUrl: null,
    vscodeId: "scarletdev.crimson-code",
    trendingScore: 62.8,
  },
  {
    id: "16",
    name: "Lavender Haze",
    publisher: "floralui",
    publisherId: "floralui",
    description: "Soft lilacs and muted lavenders over gentle cream backgrounds",
    installs: 10800,
    rating: 4.6,
    ratingCount: 72,
    lastUpdated: "2026-04-08T00:00:00Z",
    repository: "https://github.com/floralui/lavender-haze",
    type: "light",
    categories: ["lavender", "soft", "light"],
    colors: [
      { name: "Background", hex: "#f8f4fc" },
      { name: "Foreground", hex: "#3d2e5c" },
      { name: "Accent", hex: "#9b7ec8" },
      { name: "Keyword", hex: "#6b4c9a" },
      { name: "String", hex: "#7c6f8a" },
      { name: "Comment", hex: "#b8a8d0" },
      { name: "Variable", hex: "#8a6bac" },
      { name: "Function", hex: "#5a3d7a" },
    ],
    iconUrl: null,
    vscodeId: "floralui.lavender-haze",
    trendingScore: 82.1,
  },
  {
    id: "17",
    name: "Ember Glow",
    publisher: "forgefire",
    publisherId: "forgefire",
    description: "Smoldering ambers and warm golds on charcoal-black like a dying campfire",
    installs: 16700,
    rating: 4.4,
    ratingCount: 93,
    lastUpdated: "2026-03-22T00:00:00Z",
    repository: "https://github.com/forgefire/ember-glow",
    type: "dark",
    categories: ["warm", "fire", "dark"],
    colors: [
      { name: "Background", hex: "#140e08" },
      { name: "Foreground", hex: "#e8d4b8" },
      { name: "Accent", hex: "#e8943a" },
      { name: "Keyword", hex: "#f0a848" },
      { name: "String", hex: "#d4a040" },
      { name: "Comment", hex: "#6b5030" },
      { name: "Variable", hex: "#c88030" },
      { name: "Function", hex: "#f0c060" },
    ],
    iconUrl: null,
    vscodeId: "forgefire.ember-glow",
    trendingScore: 71.5,
  },
  {
    id: "18",
    name: "Toxic Hazard",
    publisher: "neonwaste",
    publisherId: "neonwaste",
    description: "Radioactive greens and hazard yellows on industrial dark gray",
    installs: 5100,
    rating: 4.3,
    ratingCount: 28,
    lastUpdated: "2026-02-18T00:00:00Z",
    repository: "https://github.com/neonwaste/toxic-hazard",
    type: "dark",
    categories: ["industrial", "neon", "dark"],
    colors: [
      { name: "Background", hex: "#0f1210" },
      { name: "Foreground", hex: "#c8e0b0" },
      { name: "Accent", hex: "#39ff14" },
      { name: "Keyword", hex: "#b0ff40" },
      { name: "String", hex: "#e0ff60" },
      { name: "Comment", hex: "#3a5a2a" },
      { name: "Variable", hex: "#80e030" },
      { name: "Function", hex: "#a0ff50" },
    ],
    iconUrl: null,
    vscodeId: "neonwaste.toxic-hazard",
    trendingScore: 77.6,
  },
  {
    id: "19",
    name: "Copper Wire",
    publisher: "retrocirc",
    publisherId: "retrocirc",
    description: "Steampunk copper tones and brass accents over dark leather backgrounds",
    installs: 8500,
    rating: 4.5,
    ratingCount: 51,
    lastUpdated: "2026-04-02T00:00:00Z",
    repository: "https://github.com/retrocirc/copper-wire",
    type: "dark",
    categories: ["steampunk", "copper", "dark"],
    colors: [
      { name: "Background", hex: "#14100c" },
      { name: "Foreground", hex: "#d8c8a8" },
      { name: "Accent", hex: "#b87333" },
      { name: "Keyword", hex: "#d4956a" },
      { name: "String", hex: "#c8a870" },
      { name: "Comment", hex: "#6b5838" },
      { name: "Variable", hex: "#a08050" },
      { name: "Function", hex: "#dab880" },
    ],
    iconUrl: null,
    vscodeId: "retrocirc.copper-wire",
    trendingScore: 80.4,
  },
  {
    id: "20",
    name: "Frostbite",
    publisher: "polartech",
    publisherId: "polartech",
    description: "Subzero blues and white frost on deep navy for a frigid coding environment",
    installs: 38000,
    rating: 4.7,
    ratingCount: 201,
    lastUpdated: "2026-04-24T00:00:00Z",
    repository: "https://github.com/polartech/frostbite",
    type: "dark",
    categories: ["cold", "blue", "dark"],
    colors: [
      { name: "Background", hex: "#0a1628" },
      { name: "Foreground", hex: "#c0d8f0" },
      { name: "Accent", hex: "#4fc3f7" },
      { name: "Keyword", hex: "#81d4fa" },
      { name: "String", hex: "#b3e5fc" },
      { name: "Comment", hex: "#2a4a6a" },
      { name: "Variable", hex: "#80cbc4" },
      { name: "Function", hex: "#4dd0e1" },
    ],
    iconUrl: null,
    vscodeId: "polartech.frostbite",
    trendingScore: 88.0,
  },
];
